### ISSUE TITLE
The Grave Bug

### ISSUE THREAD

**Issue by NimaDevy** [Atlas-Games-Repo/Fortress-defense#27]
You can play level 9 and watch. In other level is good but in this level the enemy and only one type can die but the grave not coming and player cna't win the game at all.

**Comment by NimaDevy** [comment]
Hi, I'm working on it and I fixed it actually :)

**Comment by m-nt** [comment]
لطفا کامل کن این issue رو 
![image](https://github.com/Atlas-Games-Repo/Fortress-defense/assets/68176509/f3dbd6e6-2e07-45bf-a15c-5c4a35b5c8e3)
