### ISSUE TITLE
Ability Effects error. unique Id 

### ISSUE THREAD

**Issue by amirsafaricg** [Atlas-Games-Repo/Fortress-defense#40]
Ability fx not spawning in the scene for having errors in SpawnSystemHelper.cs in GetNextObject()

![image](https://github.com/Atlas-Games-Repo/Fortress-defense/assets/77434000/dab06f8f-d7f3-47b4-8d0f-ece55dd4b56b)

https://github.com/Atlas-Games-Repo/Fortress-defense/pull/31

**Comment by m-nt** [comment]
![image](https://github.com/Atlas-Games-Repo/Fortress-defense/assets/68176509/09744e61-89ee-409f-80f5-f16b3a09ccb3)
